// Syntax: [german, english, spanish]
const strings = {
    "cancel": ["Navigation beenden", "Cancel navigation", "Terminar"],
    "next_step": ["Zum nächsten Schritt", "Next step", "Al siguiente paso"],
    "from_room": ["Von Raum", "From room", "Desde habitación"],
    "to_room": ["Nach Raum", "To room", "Después habitación"],
    "room_nr": ["Raumnummer", "Room number", "Habitación número"],
    "institute": ["Institut", "Institute", "Instituto"],
    "reached": ["erreicht", "reached", ""],
    "level": ["Etage", "Level", "Plano"],
    "Exit": ["Ausgang", "Exit", ""],
    "less_than": ["weniger als", "less then", ""],
    "meter": ["Meter", "meters", ""],
    "description_qr": ["Willkommen im GEO 1 in Münster! Bitte suchen Sie in Ihrer Umgebung den nächsten QR-Code und scannen Sie diesen. Die QR-Codes sind <b>an den Türschildern der Räume</b> installiert. Gehen Sie wie folgt vor:", "Welcome to the GEO 1 in Münster! Please search in your surrounding for the nearest QR-Code and scan it. The QR-Codes are installed <b>at the doorplates of the rooms</b>. If you don't know how to scan a QR-Code follow these instructions:", ""],
    "qr_expl_step1": ["<b>Öffnen Sie die Kamera</b> Ihres Smartphones", "<b>Open the camera</b> on your smartphone", ""],
    "qr_expl_step2": ["<b>Fokussieren</b> Sie mit der Kamera den <b>QR-Code</b>", "<b>Focus the QR-Code</b> with the camera", ""],
    "qr_expl_step3": ["Sobald die Kamera den QR-Code erkannt hat poppt ein Fenster mit der Referenz auf den Link auf. <b>Öffnen Sie dieses Fenster.</b>", "As soon as the camera recognized the QR-Code a window appears with the reference of the link saved in the QR-Code. <b>Open this window</b>", ""],
    "select_room": ["Klicken Sie auf einen Raum auf der Karte, um diesen auszuwählen", "Click on a room on the floor plan to select it", ""],
    "new_route_from_here": ["Neue Route von hier starten", "Start new route from here", ""],
    "destination_reached": ["Sie haben Ihr Ziel erreicht", "You reached your destination", ""],
    "please_turn_and_go": ["Bitte drehen Sie sich nach %s1 und laufen Sie %s2", "Please turn %s1 and walk %s2", ""],
    "destination_is_at": ["Das Ziel befindet sich ", "The destination is "],
    "left": ["links", "left", ""],
    "walk_direction_arrow": ["Bitte laufen Sie %s1 in Richtung des roten Pfeils", "Please walk %s1 in the direction of the red arrow", ""],
    "take_stairs_elevator": ["Bitte nehmen Sie %s1 ins %s2", "Please take %s1 to the %s2"],
    "the_stairs": ["die Treppen", "the stairs", ""],
    "the_elevator": ["den Fahrstuhl", "the elevator", ""],
    "right": ["rechts", "right", ""],
    "category": ["Kategorie", "Category", ""],
    "staff": ["Mitarbeiter", "Staff", ""],
    "question_only_elevator": ["Wollen Sie nur den Fahrstuhl für die Navigation verwenden?", "Do you only want to use the elevator for the navigation?", ""],
    "destermine_my_position": ["Meinen Standort bestimmen", "Determine my location", ""],
    "destermine_my_destination": ["Meinen Zielraum bestimmen", "Determine my destination", ""],
    "scan_qr_code_from_room": ["QR-Code von Raum scannen", "Scan QR-Code from room", ""],
    "select_room_on_floorplan": ["Raum auf Grundrisskarte auswählen", "Select room on floor plan", ""],
    "search_list_of_rooms": ["Liste der Räume durchsuchen", "Search list of rooms", ""],
    "chose_entry_building": ["Den Eingang vom Gebäude wählen", "Chose the entry of the building", ""],
    "reset_position": ["Ausgangsposition zurücksetzen", "Reset initial position", ""],
    "navigate_to_room": ["Zum Raum navigieren", "Navigate to room", ""],
    "start_from_here": ["Von hier starten", "Start from here", ""],
    "title_application": ["Indoor Navigation Geoinstitut Münster", "Indoor Navigation Geoinstitut Münster", "Navegación en interiores Geoinstitut Münster"],
    "autocomplete_placeholder": [" 🔍   Suche Mitarbeiter, Raumnummern, ...", " 🔍   Search staff, room numbers, ...", " 🔍   "],
    "instructions_beginning": ["Willkommen am Geoinsitut in Münster!\n\n Um einen Startpunkt oder Ziel auszuwählen, klicken Sie einfach auf einen Räume auf dem Gebäudeplan oder suchen Sie diesen im Suchfeld oben.", "", ""],
    "floor_1": ["UG", "BF"],
    "name_floor_1": ["Untergeschoss", "basement"],
    "floor_2": ["EG", "GF"],
    "name_floor_2": ["Erdgeschoss", "ground floor"],
    "floor_3": ["1. OG", "1 UL"],
    "name_floor_3": ["1. Obergeschoss", "first upper floor"],
    "floor_4": ["2. OG", "2 UL"],
    "name_floor_4": ["2. Obergeschoss", "second upper floor"],
    "floor_5": ["3. OG", "3 UL"],
    "name_floor_5": ["3. Obergeschoss", "third upper floor"],
    "floor_6": ["4. OG", "4 UL"],
    "name_floor_6": ["4. Obergeschoss", "forth upper floor"],
    "floor_7": ["5. OG", "5 UL"],
    "name_floor_7": ["5. Obergeschoss", "fifth upper floor"]
};