// Syntax: [german, english, spanish]
const strings = {
    "cancel": ["Navigation beenden", "Cancel navigation", "Terminar"],
    "next_step": ["Zum nächsten Schritt", "Next step", "Al siguiente paso"],
    "from_room": ["Von Raum", "From room", "Desde habitación"],
    "to_room": ["Nach Raum", "To room", "Después habitación"],
    "room_nr": ["Raumnummer", "Room number", "Habitación número"],
    "institute": ["Institut", "Institute", "Instituto"],
    "reached": ["erreicht", "reached", ""],
    "level": ["Etage", "Level", "Plano"],
    "Exit": ["Ausgang", "Exit", ""],
    "select_room": ["Klicken Sie auf einen Raum auf der Karte, um diesen auszuwählen", "Click on a room on the floor plan to select it", ""],
    "new_route_from_here": ["Neue Route von hier starten", "Start new route from here", ""],
    "destination_reached": ["Sie haben Ihr Ziel erreicht", "You reached your destination", ""],
    "destination_is_at": ["Das Ziel befindet sich ", "The destination is "],
    "at_top": [],
    "category": ["Kategorie", "Category", ""],
    "destermine_my_position": ["Meinen Standort bestimmen", "Determine my location", ""],
    "destermine_my_destination": ["Meinen Zielraum bestimmen", "Determine my destination", ""],
    "scan_qr_code_from_room": ["QR-Code von Raum scannen", "Scan QR-Code from room", ""],
    "select_room_on_floorplan": ["Raum auf Grundrisskarte auswählen", "Select room on floor plan", ""],
    "search_list_of_rooms": ["Liste der Räume durchsuchen", "Search list of rooms", ""],
    "reset_position": ["Ausgangsposition zurücksetzen", "Reset initial position", ""],
    "navigate_to_room": ["Zum Raum navigieren", "Navigate to room", ""],
    "start_from_here": ["Von hier starten", "Start from here", ""],
    "title_application": ["Indoor Navigation Geoinstitut Münster", "Indoor Navigation Geoinstitut Münster", "Navegación en interiores Geoinstitut Münster"],
    "autocomplete_placeholder": [" 🔍   Suche Raumnummern, Personen, ...", " 🔍   Search room numbers, persons, ...", " 🔍   "],
    "instructions_beginning": ["Willkommen am Geoinsitut in Münster!\n\n Um einen Startpunkt oder Ziel auszuwählen, klicken Sie einfach auf einen Räume auf dem Gebäudeplan oder suchen Sie diesen im Suchfeld oben.", "", ""],
    "floor_1": ["UG", "BF"],
    "floor_2": ["EG", "GF"],
    "floor_3": ["1. OG", "1 UL"],
    "floor_4": ["2. OG", "2 UL"],
    "floor_5": ["3. OG", "3 UL"],
    "floor_6": ["4. OG", "4 UL"],
    "floor_7": ["5. OG", "5 UL"]
};