// Syntax: [german, english, spanish]
const strings = {
    "cancel": ["Navigation beenden", "Cancel navigation", "Terminar"],
    "next_step": ["Zum nächsten Schritt", "Next step", "Al siguiente paso"],
    "from_room": ["Von Raum", "From room", "Desde habitación"],
    "to_room": ["Nach Raum", "To room", "Después habitación"],
    "room_nr": ["Raumnummer", "Room number", "Habitación número"],
    "institute": ["Institut", "Institute", "Instituto"],
    "reached": ["erreicht", "reached", ""],
    "level": ["Etage", "Level", "Plano"],
    "Exit": ["Ausgang", "Exit", ""],
    "new_route_from_here": ["Neue Route von hier starten", "Start new route from here", ""],
    "destination_reached": ["Sie haben Ihr Ziel erreicht", "You reached your destination", ""],
    "destination_is_at": ["Das Ziel befindet sich ", "The destination is "],
    "at_top": [],
    "reset_position": ["Ausgangsposition zurücksetzen", "Reset initial position", ""],
    "navigate_to_room": ["Zum Raum navigieren", "Navigate to room", ""],
    "start_from_here": ["Von hier starten", "Start from here", ""],
    "title_application": ["Indoor Navigation Geoinstitut Münster", "Indoor Navigation Geoinstitut Münster", "Navegación en interiores Geoinstitut Münster"],
    "autocomplete_placeholder": ["Suche Raumnummern, Personen, ...", "Search room numbers, persons, ..."],
    "floor_1": ["UG", "BF"],
    "floor_2": ["EG", "GF"],
    "floor_3": ["1. OG", "1 UL"],
    "floor_4": ["2. OG", "2 UL"],
    "floor_5": ["3. OG", "3 UL"],
    "floor_6": ["4. OG", "4 UL"],
    "floor_7": ["5. OG", "5 UL"]
};